version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/butterfly.lpk

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: butterfly

build:
  run_buildscript: false

images:
  - id: butterfly
    target: service
    service: butterfly
    source: linwooddev/butterfly
    channel: stable
    tag_regex: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: true
    skip_if_version_exists: true
    create_if_missing: true
    changelog_locales: [zh, en]
    application:
      language: zh
      name: Butterfly
      source: https://github.com/LinwoodDev/Butterfly
      source_author: LinwoodDev
  private:
    enabled: true
    skip_if_version_exists: true
    name: Butterfly
    summary: 高效简洁手绘笔记工具
