application:
  subdomain: butterfly
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://butterfly:80/
services:
  butterfly:
    # linwooddev/butterfly:v2.3.0
    # upstream: linwooddev/butterfly:v2.5.3
    image: registry.lazycat.cloud/czyt/linwooddev/butterfly:21acaedb0d9a4c52
